version: "3.1"

services:
  mysqlpractice:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    restart: always
    ports:
    - 7777:80
    volumes:
    - /sessions